version: '3.1'
services:

  krill:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: kyokley/krill-base
    command: krill -u 30 -S /app/test_sources.txt
    volumes:
      - .:/app
      - ~/.bash_history_krill:/root/.bash_history
