[tool.poetry]
name = "krill"
version = "0.1.0"
description = ""
authors = ["Kevin Yokley <kyokley2@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31"
beautifulsoup4 = "^4.8"
feedparser = "^6.0"
blessings = "^1.7"
cryptography = "^41.0"
unsync = "^1.4.0"
httpx = "^0.27.2"

[tool.poetry.dev-dependencies]
bpython = {version = "^0.18.0", allow-prereleases = true}
black = {version = "^18.3-alpha.0", allow-prereleases = true}
isort = "^4.3"
pdbpp = "^0.10.2"
pytest = "^7.2"

[tool.poetry.scripts]
krill = 'krill.krill:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
